Initial travis support for autotools

diff --git a/script/travis b/script/travis
--- a/script/travis
+++ b/script/travis
@@ -58,5 +58,13 @@ else
   exit 1
 fi
 
-ROOTDIR=`cd $(dirname $0) && pwd -P`
-$ROOTDIR/docker-run bassosimone/mk-debian:testing cmake
+ROOTDIR=`cd $(dirname $0)/../../../ && pwd -P`
+if [ -x ./autogen.sh ]; then
+  BUILD_TOOL=autotools
+elif [ -f CMakeLists.txt ]; then
+  BUILD_TOOL=cmake
+else
+  echo "$0: cannot determine build system type" 1>&2
+  exit 1
+fi
+$ROOTDIR/docker-run bassosimone/mk-debian:testing $BUILD_TOOL
